### ISSUE TITLE
Unable to execute parallel_apply on Rolling DataFrame with Time Interval as Window 

### ISSUE THREAD

**Issue by dice89** [nalepae/pandarallel#60]
Hi there, 
When working with time intervals on the rolling operation I get an error. When you execute the minimum example code, an error as on the bottom of this issue will pop up.
```
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize(nb_workers=2)
from datetime import datetime
cc_trans = pd.DataFrame([{"DateTime":datetime.now(),"CardNo":1, "Amount":7},{"DateTime":datetime.now(),"CardNo":2,"Amount":4}])

grouped_cc = cc_trans.set_index('DateTime').groupby('CardNo')

interval='1D'
group_by_card_and_date_rolling = grouped_cc.rolling(interval,win_type="triang")
sum_revenue = group_by_card_and_date_rolling.Amount.parallel_apply(pd.core.window.Rolling.sum)
```
Error:
```
INFO: Pandarallel will run on 2 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/pandarallel/pandarallel.py", line 46, in global_worker
    return _func(x)
  File "/usr/local/lib/python3.6/dist-packages/pandarallel/pandarallel.py", line 82, in wrapper
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pandarallel/data_types/rolling_groupby.py", line 33, in worker
    item = df.rolling(**attribute2value).apply(func, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 10769, in rolling
    closed=closed,
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/window.py", line 2847, in rolling
    return Window(obj, win_type=win_type, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/window.py", line 93, in __init__
    self.validate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/window.py", line 649, in validate
    raise ValueError("Invalid win_type {0}".format(self.win_type))
ValueError: Invalid win_type freq
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-21-fc3588114435> in <module>
      9 interval='1D'
     10 group_by_card_and_date_rolling = grouped_cc.rolling(interval,win_type="triang")
---> 11 sum_revenue = group_by_card_and_date_rolling.Amount.parallel_apply(pd.core.window.Rolling.sum)

/usr/local/lib/python3.6/dist-packages/pandarallel/pandarallel.py in closure(data, func, *args, **kwargs)
    384                 input_files,
    385                 output_files,
--> 386                 map_result,
    387             )
    388 

/usr/local/lib/python3.6/dist-packages/pandarallel/pandarallel.py in get_workers_result(use_memory_fs, nb_workers, show_progress_bar, nb_columns, queue, chunk_lengths, input_files, output_files, map_result)
    329                 progress_bars.update(progresses)
    330 
--> 331     results = map_result.get()
    332 
    333     return (

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

ValueError: Invalid win_type freq

```
My pandas version is:'0.25.2'
And im Running on python 3.6

Any idea how to fix this issue, willing to contribute here :)

**Comment by nalepae** [comment]
Fixed in `pandarallel v1.4.3`.

Thanks!

**Comment by ogabrielluiz** [comment]
It seems this still happens in DataFrame.rolling().parallel_apply().

Using version 1.4.5 on GoogleColab and pandas 0.25.3.

**Comment by rtadewald** [comment]
> It seems this still happens in DataFrame.rolling().parallel_apply().
> 
> Using version 1.4.5 on GoogleColab and pandas 0.25.3.

Same issue here.

**Comment by DonIvanCorleone** [comment]
Same issue here: 

pandarallel                   1.5.2
pandas                        1.1.1
